### PR TITLE
fix!: correctly report async Kafka sink errors, retry always. Fixes #494

### LINKED ISSUE #494: "Async to Kafka failed"  means messages are lost
* [x] Check that the metrics are correctly reported.
* [ ] Should we be throttling the source? Other config to consider.

### PR DESCRIPTION
**Pull request by alexec**

### CODE REVIEW

**Comment by alexec** [comment]
@sarabala1979 I think this is historical problem.

File: runner/sidecar/sink/kafka/kafka.go [hunk 1]
```diff
@@ -26,23 +26,7 @@ type kafkaSink struct {
 	async    bool
 }
 
-var kafkaMessagesProducedSuccess, kafkaMessagesProducedErr *prometheus.CounterVec
-
-func init() {
-	// track async success and errors
-	kafkaMessagesProducedSuccess = promauto.NewCounterVec(prometheus.CounterOpts{
```
Comment (alexec) [inline runner/sidecar/sink/kafka/kafka.go:33]: removed completely, was not using this

**Review by sarabala1979 — APPROVED** [review]
